# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: structured-roadmap

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: sroadmap
    binary: sroadmap
    main: ./cmd/sroadmap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: grokify
    name: structured-roadmap
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: structured-roadmap
    repository:
      owner: grokify
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/grokify/structured-roadmap"
    description: "CLI for machine-readable project roadmaps using JSON IR"
    license: "MIT"
    install: |
      bin.install "sroadmap"
      bin.install_symlink "sroadmap" => "structured-roadmap"
    test: |
      system "#{bin}/sroadmap", "version"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
