// Package renderer provides Markdown generation from TaskList IR.
package renderer

// GroupBy specifies how to group tasks.
type GroupBy string

const (
	GroupByArea   GroupBy = "area"
	GroupByType   GroupBy = "type"
	GroupByPhase  GroupBy = "phase"
	GroupByStatus GroupBy = "status"
)

// Options controls how the task list is rendered to Markdown.
type Options struct {
	// GroupBy determines how tasks are grouped.
	GroupBy GroupBy

	// ShowCompleted includes completed tasks in output.
	ShowCompleted bool

	// UseCheckboxes renders tasks as [ ] and [x] syntax.
	UseCheckboxes bool

	// UseEmoji includes emoji status indicators.
	UseEmoji bool

	// ShowLegend renders a legend table at the top.
	ShowLegend bool

	// ShowTOC renders a table of contents at the top.
	ShowTOC bool

	// TOCDepth controls TOC nesting: 1 = sections only, 2 = sections + tasks.
	TOCDepth int

	// NumberItems adds numbers before task titles.
	NumberItems bool

	// HorizontalRules adds --- between major sections.
	HorizontalRules bool

	// ShowIntro renders an introductory paragraph at the top.
	ShowIntro bool

	// IntroText is custom intro text. If empty, uses default.
	IntroText string

	// ShowOverviewTable renders a summary table of all tasks at the top.
	ShowOverviewTable bool

	// ShowAreaSubheadings shows area groupings within phase sections.
	// Only applies when GroupBy is set to GroupByPhase.
	ShowAreaSubheadings bool

	// ShowNavLinks adds navigation links (e.g., "Top" links in section headings).
	ShowNavLinks bool
}

// DefaultIntroText is the standard introductory paragraph.
const DefaultIntroText = `This task list documents planned and completed features for this project.

The format is based on and generated by [Structured Tasks](https://github.com/grokify/structured-tasks), which provides a machine-readable JSON intermediate representation with deterministic Markdown generation.`

// DefaultOptions returns sensible default rendering options.
func DefaultOptions() Options {
	return Options{
		GroupBy:             GroupByArea,
		ShowCompleted:       true,
		UseCheckboxes:       true,
		UseEmoji:            true,
		ShowLegend:          false,
		ShowIntro:           true,
		IntroText:           "",
		ShowTOC:             false,
		TOCDepth:            1,
		ShowOverviewTable:   true,
		ShowAreaSubheadings: false,
		ShowNavLinks:        true,
		NumberItems:         false,
		HorizontalRules:     true,
	}
}

// WithGroupBy sets the grouping strategy.
func (o Options) WithGroupBy(g GroupBy) Options {
	o.GroupBy = g
	return o
}

// WithCheckboxes enables or disables checkbox syntax.
func (o Options) WithCheckboxes(enabled bool) Options {
	o.UseCheckboxes = enabled
	return o
}

// WithEmoji enables or disables emoji status indicators.
func (o Options) WithEmoji(enabled bool) Options {
	o.UseEmoji = enabled
	return o
}

// WithLegend enables or disables the legend section.
func (o Options) WithLegend(enabled bool) Options {
	o.ShowLegend = enabled
	return o
}

// WithNumberedItems enables or disables numbered items.
func (o Options) WithNumberedItems(enabled bool) Options {
	o.NumberItems = enabled
	return o
}
