// Package renderer provides Markdown generation from Roadmap IR.
package renderer

// GroupBy specifies how to group roadmap items.
type GroupBy string

const (
	GroupByArea     GroupBy = "area"
	GroupByType     GroupBy = "type"
	GroupByPhase    GroupBy = "phase"
	GroupByStatus   GroupBy = "status"
	GroupByQuarter  GroupBy = "quarter"
	GroupByPriority GroupBy = "priority"
)

// Options controls how the roadmap is rendered to Markdown.
type Options struct {
	// GroupBy determines how items are grouped.
	GroupBy GroupBy

	// ShowCompleted includes completed items in output.
	ShowCompleted bool

	// UseCheckboxes renders tasks as [ ] and [x] syntax.
	UseCheckboxes bool

	// UseEmoji includes emoji status indicators.
	UseEmoji bool

	// ShowLegend renders a legend table at the top.
	ShowLegend bool

	// ShowTOC renders a table of contents at the top.
	ShowTOC bool

	// TOCDepth controls TOC nesting: 1 = sections only, 2 = sections + items.
	TOCDepth int

	// ShowVersionHistory includes version history section.
	ShowVersionHistory bool

	// ShowDependencies includes dependencies section.
	ShowDependencies bool

	// ShowSections includes freeform sections.
	ShowSections bool

	// SectionOrder specifies the order of sections by ID.
	// Sections not in this list are appended at the end.
	SectionOrder []string

	// NumberItems adds numbers before item titles.
	NumberItems bool

	// HorizontalRules adds --- between major sections.
	HorizontalRules bool

	// ShowIntro renders an introductory paragraph at the top.
	ShowIntro bool

	// IntroText is custom intro text. If empty, uses default.
	IntroText string

	// ShowOverviewTable renders a summary table of all items at the top.
	ShowOverviewTable bool

	// ShowAreaSubheadings shows area groupings within phase sections.
	// Only applies when GroupBy is set to GroupByPhase.
	ShowAreaSubheadings bool
}

// DefaultIntroText is the standard introductory paragraph.
const DefaultIntroText = `This roadmap documents planned and completed features for this project.

The format is based on and generated by [Structured Roadmap](https://github.com/grokify/structured-roadmap), which provides a machine-readable JSON intermediate representation with deterministic Markdown generation.`

// DefaultOptions returns sensible default rendering options.
func DefaultOptions() Options {
	return Options{
		GroupBy:             GroupByArea,
		ShowCompleted:       true,
		UseCheckboxes:       true,
		UseEmoji:            true,
		ShowLegend:          false,
		ShowIntro:           true,
		IntroText:           "",
		ShowTOC:             false,
		TOCDepth:            1,
		ShowOverviewTable:   false,
		ShowAreaSubheadings: false,
		ShowVersionHistory:  true,
		ShowDependencies:    false,
		ShowSections:        true,
		NumberItems:         false,
		HorizontalRules:     true,
	}
}

// WithGroupBy sets the grouping strategy.
func (o Options) WithGroupBy(g GroupBy) Options {
	o.GroupBy = g
	return o
}

// WithCheckboxes enables or disables checkbox syntax.
func (o Options) WithCheckboxes(enabled bool) Options {
	o.UseCheckboxes = enabled
	return o
}

// WithEmoji enables or disables emoji status indicators.
func (o Options) WithEmoji(enabled bool) Options {
	o.UseEmoji = enabled
	return o
}

// WithLegend enables or disables the legend section.
func (o Options) WithLegend(enabled bool) Options {
	o.ShowLegend = enabled
	return o
}

// WithNumberedItems enables or disables numbered items.
func (o Options) WithNumberedItems(enabled bool) Options {
	o.NumberItems = enabled
	return o
}
